import createClient from "openapi-fetch";
import type { paths } from "@/schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: import.meta.env.VITE_API_URL });

export async function getProduct() {
  const { data, error } = await client.GET("/products");

  console.log({ data, error });
}
