import createFeatchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/schema"; // generated by openapi-typescript

const featchClient = createFeatchClient<paths>({
  baseUrl: import.meta.env.VITE_API_URL,
});

export const $api = createClient(featchClient);
